spring:
  application:
    name: data.miner
  config:
    activate:
      on-profile: default
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://tfm-postgres.postgres.database.azure.com:5432/tfm-postgres
    username: ivan_klp@tfm-postgres
    password: Tfm_1234
    driver-class-name: org.postgresql.Driver
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#    show-sql: false
#  h2:
#    console:
#      enabled: true
#  datasource:
#    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
    #data: classpath:testdata.sql

server:
  port: 8080

---
spring:
  config:
    activate:
      on-profile: production
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    url: jdbc:sqlserver://tfm-bbdd.database.windows.net:1433;databaseName=tfm-data
    username: ivan_klp@tfm-bbdd
    password: Tfm_1234
    driver-class-name: org.postgresql.Driver

